### ISSUE TITLE
Add a README.md file

### ISSUE THREAD

**Issue by anijit18** [OpenSource-UIT/hacktoberfest-24-1#2]
This README file provides a comprehensive guide for contributors to successfully install, configure, and run the application locally. Following the outlined steps ensures a seamless setup and development experience.

I want to work on this issue.

Kindly assign it to me under Hacktoberfest2024.
@hridyesh-gupta

**Comment by MrSwapnilRahate** [comment]
I'm ready contribute. Please assign this to me under Hacktoberfest2024.

**Comment by proheroabhi** [comment]
I want to contribute in this. Please assign me this.
