### ISSUE TITLE
Feature: Allow Dynamic Player Names

### ISSUE THREAD

**Issue by Ashwani1621** [OpenSource-UIT/hacktoberfest-24-1#6]
Allow players to enter their names at the start, which will be shown instead of "X" and "O".

**Comment by aaryak1369** [comment]
@Ashwani1621  I'd like to start working on this

**Comment by aaryak1369** [comment]
@Ashwani1621 i have created a pull request wherein i solved this issue, please check it out

**Comment by aaryak1369** [comment]
@hridyesh-gupta if you wish to, you can close this issue now since you successfully merged a pr.
